version: '3.7'

x-base-dev: &base-dev
  restart: on-failure
  volumes:
    - .:/project
  working_dir: /project/tex

services:
  xelatex:
    <<: *base-dev
    image: salimfadhley/jinja2cli:latest
    build:
      context: .
      target: xelatex
    entrypoint: ["xelatex"]

  jinja2cli:
    <<: *base-dev
    image: salimfadhley/xelatex:latest
    build:
      context: .
      target: xelatex


